### ISSUE TITLE
msg.BtcDecode returns the wrong hash for the mweb transaction

### ISSUE THREAD

**Issue by CMajeri** [ltcsuite/ltcd#17]
Hello,

The hash for the mweb tx 
https://chainz.cryptoid.info/ltc/tx.dws?116044867.htm
is wrong.
This is due to the locktime being read from the wrong place (i don't know where the right place is, but it should be 0)

**Comment by CMajeri** [comment]
In the C code:

```
    if (flags & 1) {
        for (size_t i = 0; i < tx.vin.size(); i++) {
            s << tx.vin[i].scriptWitness.stack;
        }
    }
    if (flags & 8) {
        s << tx.mweb_tx;
    }
    s << tx.nLockTime;
 ```
 
 witnesses aren't serialized for the mweb tx, however the lib still tries to parse them.
 For now I will fork this, and set the locktime to 0 for the mweb manually, I'll try to dig more tomorrow

**Comment by losh11** [comment]
hey @CMajeri, another user just submitted PR #15 which skips blockdecode on mweb txs. You can rebuild ltcd in the meanwhile if it's urgent, and if you are able to get MWEB tx decoding working, that would be awesome also.

**Comment by CMajeri** [comment]
Hi, yes I saw the commit, that's what prompted me to open this issue :)

Even after it, the hash for the mweb tx is wrong, also, it tries to read the witnesses which shouldn't be there (according to the transaction.h file)

**Comment by losh11** [comment]
great, looking forward to hearing from you tomorrow!

**Comment by zhenyuzhao-cb** [comment]
From the code, decoder checks "hasWitness" flag before decode witness part.
The go version looks equivalent with the c++ version :
- go: https://github.com/ltcsuite/ltcd/blob/master/wire/msgtx.go#L570-L605
- c++: https://github.com/litecoin-project/litecoin/blob/v0.21.2/src/primitives/transaction.h#L360-L364

**Comment by CMajeri** [comment]
You're right, for some reason I thought hasWitness was set alongside hasMweb

**Comment by CMajeri** [comment]
The few last txs I've seen end in "00 00000000" which could mean "size of mweb tx is 0" and the 4 remaining 0s are the lock time.
I'm trying to find how the mweb tx is encoded in the Cpp code to actually fix this.

**Comment by losh11** [comment]
hey @CMajeri did you make any progress on this? It'd be nice to have this ready before I make the final lnd 0.14.2 tag. let me know if you have any questions, and I can get you in contact with David Burkett to help solve this issue.

**Comment by losh11** [comment]
hey @CMajeri did you manage to fix this?

**Comment by chappjc** [comment]
I recently had to write tx and block deserialization Go code to work with litecoind v0.21.2.  This following commit may be of help for this issue: https://github.com/decred/dcrdex/pull/1536/commits/dd71d460852c19c345da8a5869000ad3dc9a1beb

As the issue here noted, you have to actually properly deserialize the *variable length* mw section of the tx to get to the correct lockTime value.  When working on txns in blocks, this isn't an issue because the mw section is just a single null byte (if the tx flag indicates it should be there) because this is the HogEx, meaning you just throw out a single byte and then read the lockTime.  However, for txn in mempool like the pegins you really do need to deserialize the mw section properly rather than simply discarding a single byte to get to the lockTime.  See `DeserializeTx` in dex/networks/ltc/tx.go and `DeserializeBlock` in dex/networks/ltc/block.go

Clearly if you are deserializing a buffer that only contains the transaction, you can read the whole thing and get the lockTime as the last four bytes, but if you are working with a buffer that is the block and you don't know the length of the transaction bytes within the raw block, you need to decode the mw section of the txn (which in the HobEx seems to be just a single zero byte).  This is where doing `ioutil.ReadAll(r)` could be a problem depending on the `io.Reader`.

The linked commit also deserializes blocks with MWEBs appended in the same way as the reference C++ code.

**Comment by losh11** [comment]
Currently WIP in the `mweb` branch. Mostly just repurposing @chappjc's work! Thank you for that :)

I'm having an issue with 1/6 of the test - the expected kernel size is 2 bytes longer than the one I'm getting. Very weird. Can anyone help?

**Comment by chappjc** [comment]
@losh11 Sorry, that API could be more versatile.  How's https://github.com/ltcsuite/ltcd/commit/5618021653ae7d0d037611e725e03b39e1053bab?

**Comment by losh11** [comment]
Great! Would appreciate reviews before merging into the main branch.

**Comment by losh11** [comment]
Closing due to #31!
